### PR TITLE
Add support for new models

### PR DESCRIPTION
**Pull request by dandri**
fixes

### CODE REVIEW

**Comment by david4599** [comment]
Follow-up to #3 

Yep these are new models I haven't seen before and I am glad to see that they work with PricehaxBT, they didn't change the image format to send.
Did you try to upload an image containing red color?
The black/white/red version seems common nowaydays and I am not sure if these ones you added support color or if they are black/white only.

From the pictures, I see that the 1243 is an E4 HCW (W is for Wide) but the segments mapping may be different from the other Continuum models. If that's the case, the ESL will display random segments and we would need to check manually one segment at a time to know which bit corresponds to which segment.
For now, you can just set it like I did for the promoline version:

```java
case 1243:
    MainActivity.this.scaneitype.setText("Type: " + MainActivity.this.PLType + " (Continuum E4 HCW (18410-00) segments bitmap not done !)");
    MainActivity.this.ESLType = 1;
    break;
```

FYI, there is no barcode behind the sticker on Continuum ones, only at the back.

Also, for the models you tested with success, you can remove the "EXPERIMENTAL" text.

**Comment by dandri** [comment]
Im not sure if they support red color or not but I can try sometime soon to see.
I will update mainactivity and remove the experimental line and change for the 1243 one

**Comment by dandri** [comment]
1628 supports Red but not the 1315
SmartSelect_20230430_204821_Pricehax BT

**Comment by david4599** [comment]
Nice!
I have just re-added the 1242 model that you replaced by mistake and removed the EXPERIMENTAL text for the 1315 model.

Also, quick note about GitHub references: You set the commit message "fix hashtag2" which created a reference to the pull request 2 that has nothing to do with this one. Don't use #number as a way of incrementing something. It should be only used to reference other issues or pull requests. Not a big deal here but on other projects, that can be annoying.

**Comment by dandri** [comment]
Awesome
Thank you for the help and notes i appreciate it

**Pull request merged**
